# Generated by `mix grpc.gen.server`.
# Please implement all functions.
defmodule StressTest.StressService.Server do
  use GRPC.Server, service: StressTest.StressService.Service

  def stress_call(stress_request, _stream) do
    StressTest.StressResponse.new(reply: "qwerty")
  end

end
