# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: stress.proto for package 'stress_test'

require 'grpc'
require_relative 'stress_pb'

module StressTest
  module StressService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'stress_test.StressService'

      rpc :StressCall, StressRequest, StressResponse
    end

    Stub = Service.rpc_stub_class
  end
end
