# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stress.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "stress_test.Error" do
    optional :code, :int32, 1
    optional :message, :string, 2
    optional :type, :enum, 3, "stress_test.Error.Type"
  end
  add_enum "stress_test.Error.Type" do
    value :SUCCESS, 0
    value :INTERNAL, 1
    value :UNKNOWN, 2
    value :VALIDATION, 3
  end
  add_message "stress_test.Person" do
    optional :first_name, :string, 1
    optional :last_name, :string, 2
    optional :weight, :float, 3
  end
  add_message "stress_test.Duration" do
    optional :type, :enum, 1, "stress_test.Duration.Type"
    optional :duration_sec, :int32, 2
  end
  add_enum "stress_test.Duration.Type" do
    value :SECONDS, 0
    value :RANDOM, 1
  end
  add_message "stress_test.StressRequest" do
    optional :version, :string, 1
    repeated :persons, :message, 2, "stress_test.Person"
    optional :duration, :message, 3, "stress_test.Duration"
  end
  add_message "stress_test.StressResponse" do
    optional :reply, :string, 1
    optional :error, :message, 2, "stress_test.Error"
    repeated :persons, :message, 3, "stress_test.Person"
  end
end

module StressTest
  Error = Google::Protobuf::DescriptorPool.generated_pool.lookup("stress_test.Error").msgclass
  Error::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("stress_test.Error.Type").enummodule
  Person = Google::Protobuf::DescriptorPool.generated_pool.lookup("stress_test.Person").msgclass
  Duration = Google::Protobuf::DescriptorPool.generated_pool.lookup("stress_test.Duration").msgclass
  Duration::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("stress_test.Duration.Type").enummodule
  StressRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("stress_test.StressRequest").msgclass
  StressResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("stress_test.StressResponse").msgclass
end
